language: node_js
node_js:
- '7'
- '8'
- '9'
- '10'
notifications:
  slack:
    secure: Yloz3a613jSdCiYTwqjyaGtCc3rex4xMVWFUFksyr2oxBzdt+xv6IQ7JJiHx06lLN+FxYl3GIW1vgbJDnGpEuNEzp/6hOQqeIgk9wPNQDcizcqSwCS7q95qXqGN9GW4hR5jNX4zKRukpCaAgpWAk5JZK6uHaeYMiUsjSJRHo7ZCDQCWtFoHEV2M1Gi3jsZRvWt6hhLb4SdlVNbndtL1NSlezjGj/6rG+liaQuH4gbDvcMJpMSd9ry4GOhK8JQe0fB00ZlB729rONNizuUm0RWuacYoK8gzkao3/h8zp4UQW0Dv6vL1HSFMypdH8HjTFMPsaaHpRxGwaqb94P+duCEU7oZHOhpZHjcX/0qNozh0o6m97yeCOsPURwPMidJN7EP3Hub2tGZ1zQ0x3zodXAOiz+eP777s7mJAyaXgKz3/DuciXft/t6YfhRK9FZ9Yu7xIC2A+JKEQKn1emUD4SXpyvSI02l25V6XgW/ruHtrPTzbZX0Uj6Z5VndsMHlO5MSjGHodNcGUeiHzBbU+DeDtHm7arCSenCSLu1x9TwEoRIpnmc3m0yJcSJys5pmH9viObpBeCL77JY4I9s4FJuX05BO/AhgeAkIgZg6Dq2Vj1ADF5YWZtKPKnByjyERHcZK+Qe0gYsQNjx63orLVbOTLFm2UqCNCoIQYHUJqS/aWSw=
